/*
Adept MobileRobots Advanced Robotics Navigation and Localization (ARNL)
Version 1.9.0

Copyright (C) 2004, 2005 ActivMedia Robotics LLC
Copyright (C) 2006-2009 MobileRobots Inc.
Copyright (C) 2010-2014 Adept Technology, Inc.

All Rights Reserved.

Adept MobileRobots does not make any representations about the
suitability of this software for any purpose.  It is provided "as is"
without express or implied warranty.

The license for this software is distributed as LICENSE.txt in the top
level directory.

robots@mobilerobots.com
Adept MobileRobots
10 Columbia Drive
Amherst, NH 03031
+1-603-881-7960

*/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Arnl;

  import com.mobilerobots.Aria.*; 
  import com.mobilerobots.ArNetworking.*;
  import com.mobilerobots.BaseArnl.*;

public interface ArnlJavaConstants {
  public final static int ARNL = ArnlJavaJNI.ARNL_get();
  public final static int SWIG_IMPORTED_ARIA = ArnlJavaJNI.SWIG_IMPORTED_ARIA_get();
  public final static int SWIG_IMPORTED_ARNETWORKING = ArnlJavaJNI.SWIG_IMPORTED_ARNETWORKING_get();
  public final static int SWIG_IMPORTED_ARNL_BASE = ArnlJavaJNI.SWIG_IMPORTED_ARNL_BASE_get();
}
