/*
Adept MobileRobots Advanced Robotics Navigation and Localization (ARNL)
Version 1.9.0

Copyright (C) 2004, 2005 ActivMedia Robotics LLC
Copyright (C) 2006-2009 MobileRobots Inc.
Copyright (C) 2010-2014 Adept Technology, Inc.

All Rights Reserved.

Adept MobileRobots does not make any representations about the
suitability of this software for any purpose.  It is provided "as is"
without express or implied warranty.

The license for this software is distributed as LICENSE.txt in the top
level directory.

robots@mobilerobots.com
Adept MobileRobots
10 Columbia Drive
Amherst, NH 03031
+1-603-881-7960

*/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Arnl;

  import com.mobilerobots.Aria.*;
  import com.mobilerobots.ArNetworking.*;
  import com.mobilerobots.BaseArnl.*;

public class ArServerModeDockLynx extends ArServerModeDockTriangleBumpBackwards {
  private long swigCPtr;

  /* for internal use by swig only */
  public ArServerModeDockLynx(long cPtr, boolean cMemoryOwn) {
    super(ArnlJavaJNI.SWIGArServerModeDockLynxUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArServerModeDockLynx obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArnlJavaJNI.delete_ArServerModeDockLynx(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void restoreFromDockFile() {
    ArnlJavaJNI.ArServerModeDockLynx_restoreFromDockFile(swigCPtr, this);
  }

  public boolean isDocked() {
    return ArnlJavaJNI.ArServerModeDockLynx_isDocked(swigCPtr, this);
  }

  public void enableDock() {
    ArnlJavaJNI.ArServerModeDockLynx_enableDock(swigCPtr, this);
  }

  public void disableDock() {
    ArnlJavaJNI.ArServerModeDockLynx_disableDock(swigCPtr, this);
  }

  public void checkDock() {
    ArnlJavaJNI.ArServerModeDockLynx_checkDock(swigCPtr, this);
  }

  public void beforeDriveInCallback() {
    ArnlJavaJNI.ArServerModeDockLynx_beforeDriveInCallback(swigCPtr, this);
  }

  public void afterDriveOutCallback() {
    ArnlJavaJNI.ArServerModeDockLynx_afterDriveOutCallback(swigCPtr, this);
  }

}
